(defproject records "0.1.0-SNAPSHOT"
  :description "For looking at bytecode generated by defrecord"
  :url "http://example.com/FIXME"
  :xmain records.core  ; Apparently need :main for aot to work?
  :dependencies [[org.clojure/clojure "1.5.1"]])
